[tool.poetry]
name = "djangotutorial"
version = "0.1.0"
description = ""
authors = ["Deborah Iori"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.2.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
